In [8]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [9]:
data = [
    ['nico', 1, '2023-11-21 13:00:00', '2023-11-21 18:00:00', '2023-11-21 18:00:00', '2023-11-21 20:00:00', '2023-11-21 13:15:00', '2023-11-21 13:30:00'],
    ['nico', 2, '2023-11-21 13:00:00', '2023-11-21 18:00:00', '2023-11-21 18:00:00', '2023-11-21 20:00:00', '2023-11-21 13:15:00', '2023-11-21 13:45:00'],
    ['nico', 3, '2023-11-21 13:00:00', '2023-11-21 18:00:00', '2023-11-21 18:00:00', '2023-11-21 20:00:00', '2023-11-21 13:30:00', '2023-11-21 14:00:00'],
    ['nico', 4, '2023-11-21 13:00:00', '2023-11-21 18:00:00', '2023-11-21 18:00:00', '2023-11-21 20:00:00', '2023-11-21 17:30:00', '2023-11-21 18:30:00'],
    ['nico', 5, '2023-11-21 13:00:00', '2023-11-21 18:00:00', '2023-11-21 18:00:00', '2023-11-21 20:00:00', '2023-11-21 19:00:00', '2023-11-21 19:30:00'],
    ['pepe', 6, '2023-11-21 13:00:00', '2023-11-21 18:00:00', '2023-11-21 11:00:00', '2023-11-21 13:00:00', '2023-11-21 11:15:00', '2023-11-21 14:00:00'],
    ['pepe', 7, '2023-11-21 13:00:00', '2023-11-21 18:00:00', '2023-11-21 11:00:00', '2023-11-21 13:00:00', '2023-11-21 15:00:00', '2023-11-21 16:30:00'],
    ['pepe', 8, '2023-11-21 13:00:00', '2023-11-21 18:00:00', '2023-11-21 11:00:00', '2023-11-21 13:00:00', '2023-11-21 15:00:00', '2023-11-21 17:30:00'],
    ['pepe', 9, '2023-11-21 13:00:00', '2023-11-21 18:00:00', '2023-11-21 11:00:00', '2023-11-21 13:00:00', '2023-11-21 16:00:00', '2023-11-21 17:30:00']]


cols = ['name', 'task', 'RosterStart', 'RosterEnd', 'OvertimeStart', 'OvertimeEnd', 'TaskStart', 'TaskEnd']

df = pd.DataFrame(data=data, columns=cols)

df['RosterStart'] = pd.to_datetime(df['RosterStart'])
df['RosterEnd'] = pd.to_datetime(df['RosterEnd'])
df['OvertimeStart'] = pd.to_datetime(df['OvertimeStart'])
df['OvertimeEnd'] = pd.to_datetime(df['OvertimeEnd'])
df['TaskStart'] = pd.to_datetime(df['TaskStart'])
df['TaskEnd'] = pd.to_datetime(df['TaskEnd'])

In [10]:
df

,name,task,RosterStart,RosterEnd,OvertimeStart,OvertimeEnd,TaskStart,TaskEnd
0,nico,1,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 18:00:00,2023-11-21 20:00:00,2023-11-21 13:15:00,2023-11-21 13:30:00
1,nico,2,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 18:00:00,2023-11-21 20:00:00,2023-11-21 13:15:00,2023-11-21 13:45:00
2,nico,3,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 18:00:00,2023-11-21 20:00:00,2023-11-21 13:30:00,2023-11-21 14:00:00
3,nico,4,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 18:00:00,2023-11-21 20:00:00,2023-11-21 17:30:00,2023-11-21 18:30:00
4,nico,5,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 18:00:00,2023-11-21 20:00:00,2023-11-21 19:00:00,2023-11-21 19:30:00
5,pepe,6,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 11:00:00,2023-11-21 13:00:00,2023-11-21 11:15:00,2023-11-21 14:00:00
6,pepe,7,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 11:00:00,2023-11-21 13:00:00,2023-11-21 15:00:00,2023-11-21 16:30:00
7,pepe,8,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 11:00:00,2023-11-21 13:00:00,2023-11-21 15:00:00,2023-11-21 17:30:00
8,pepe,9,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 11:00:00,2023-11-21 13:00:00,2023-11-21 16:00:00,2023-11-21 17:30:00

In [11]:
# Compute Task start and end taking into account Roster and Overtime Start and End
df['RosterTaskStart'] = np.where(df.TaskStart > df.RosterStart, df.TaskStart, df.RosterStart)
df['RosterTaskEnd'] = np.where(df.TaskEnd <= df.RosterEnd, df.TaskEnd, df.RosterEnd)
df['OvertimeTaskStart'] = np.where((df.TaskStart > df.OvertimeStart) & (df.TaskStart <= df.OvertimeEnd), df.TaskStart, df.OvertimeStart)
df['OvertimeTaskEnd'] = np.where((df.TaskEnd <= df.OvertimeEnd) & (df.TaskEnd > df.OvertimeStart), df.TaskEnd, df.OvertimeEnd)

# Shifting next Task starting time into a new column to compare
df['nextTaskStartRoster'] = df.sort_values('TaskStart').groupby('name')['RosterTaskStart'].shift(-1)
df['nextTaskStartOvertime'] = df.sort_values('TaskStart').groupby('name')['OvertimeTaskStart'].shift(-1)

# Overlapping times
df['overlapRoster'] = round((df.RosterTaskEnd - df.nextTaskStartRoster).dt.total_seconds() / 60 ,2)
df['overlapOvertime'] = round((df.OvertimeTaskEnd - df.nextTaskStartOvertime).dt.total_seconds() / 60 ,2)
df.loc[df['overlapRoster'] < 0, 'overlapRoster'] = 0
df.loc[df['overlapOvertime'] < 0, 'overlapOvertime'] = 0
df['overlapRoster'] = df['overlapRoster'].fillna(0)
df['overlapOvertime'] = df['overlapOvertime'].fillna(0)

# Task Roster and Overlap elapsed time
df['TaskElapsed'] = round((df.TaskEnd - df.TaskStart).dt.total_seconds() / 60, 2)

df['RosterElapsed'] = round((df.RosterTaskEnd - df.RosterTaskStart).dt.total_seconds() / 60, 2)
df['OvertimeElapsed'] = round((df.OvertimeTaskEnd - df.OvertimeTaskStart).dt.total_seconds() / 60, 2)

df.loc[df['RosterElapsed'] < 0, 'RosterElapsed'] = 0
df.loc[df['OvertimeElapsed'] < 0, 'OvertimeElapsed'] = 0

# Computing total overlap and total time in roster and overtime
df[['overlapRoster_tot', 'RosterElapsed_tot', 'overlapOvertime_tot', 'OvertimeElapsed_tot']] = df[['name', 'TaskStart', 'overlapRoster', 'RosterElapsed', 'overlapOvertime', 'OvertimeElapsed']].sort_values('TaskStart').groupby('name')[['overlapRoster', 'RosterElapsed', 'overlapOvertime', 'OvertimeElapsed']].transform(np.sum)

df['RosterActive'] = round(df.RosterElapsed_tot - df.overlapRoster_tot, 2)
df['OvertimeActive'] = round(df.OvertimeElapsed_tot - df.overlapOvertime_tot, 2)
df['DutyActive'] = df['RosterActive'] + df['OvertimeActive']

# Computing Roster, Overtime and Duty time in shift
df['RosterShift'] = round((df.RosterEnd - df.RosterStart).dt.total_seconds() / 60, 2)
df['OvertimeShift'] = round((df.OvertimeEnd - df.OvertimeStart).dt.total_seconds() / 60, 2)
df['DutyShift'] = round(((df.RosterEnd - df.RosterStart).dt.total_seconds() / 60) + ((df.OvertimeEnd - df.OvertimeStart).dt.total_seconds() / 60), 2)

# Utilisation
df['RosterUtilisation'] = round(df['RosterActive'] / df['RosterShift'], 2)
df['OvertimeUtilisation'] = round(df['OvertimeActive'] / df['OvertimeShift'], 2 )
df['DutyUtilisation'] = round(df['DutyActive'] / df['DutyShift'], 2)

In [17]:
df

,name,task,RosterStart,RosterEnd,OvertimeStart,OvertimeEnd,TaskStart,TaskEnd,RosterTaskStart,RosterTaskEnd,OvertimeTaskStart,OvertimeTaskEnd,nextTaskStartRoster,nextTaskStartOvertime,overlapRoster,overlapOvertime,TaskElapsed,RosterElapsed,OvertimeElapsed,overlapRoster_tot,RosterElapsed_tot,overlapOvertime_tot,OvertimeElapsed_tot,RosterActive,OvertimeActive,DutyActive,RosterShift,OvertimeShift,DutyShift,RosterUtilisation,OvertimeUtilisation,DutyUtilisation
0,nico,1,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 18:00:00,2023-11-21 20:00:00,2023-11-21 13:15:00,2023-11-21 13:30:00,2023-11-21 13:15:00,2023-11-21 13:30:00,2023-11-21 18:00:00,2023-11-21 20:00:00,2023-11-21 13:15:00,2023-11-21 18:00:00,15.0,120.0,15.0,15.0,120.0,30.0,105.0,360.0,420.0,75.0,60.0,135.0,300.0,120.0,420.0,0.25,0.50,0.32
1,nico,2,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 18:00:00,2023-11-21 20:00:00,2023-11-21 13:15:00,2023-11-21 13:45:00,2023-11-21 13:15:00,2023-11-21 13:45:00,2023-11-21 18:00:00,2023-11-21 20:00:00,2023-11-21 13:30:00,2023-11-21 18:00:00,15.0,120.0,30.0,30.0,120.0,30.0,105.0,360.0,420.0,75.0,60.0,135.0,300.0,120.0,420.0,0.25,0.50,0.32
2,nico,3,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 18:00:00,2023-11-21 20:00:00,2023-11-21 13:30:00,2023-11-21 14:00:00,2023-11-21 13:30:00,2023-11-21 14:00:00,2023-11-21 18:00:00,2023-11-21 20:00:00,2023-11-21 17:30:00,2023-11-21 18:00:00,0.0,120.0,30.0,30.0,120.0,30.0,105.0,360.0,420.0,75.0,60.0,135.0,300.0,120.0,420.0,0.25,0.50,0.32
3,nico,4,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 18:00:00,2023-11-21 20:00:00,2023-11-21 17:30:00,2023-11-21 18:30:00,2023-11-21 17:30:00,2023-11-21 18:00:00,2023-11-21 18:00:00,2023-11-21 18:30:00,2023-11-21 19:00:00,2023-11-21 19:00:00,0.0,0.0,60.0,30.0,30.0,30.0,105.0,360.0,420.0,75.0,60.0,135.0,300.0,120.0,420.0,0.25,0.50,0.32
4,nico,5,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 18:00:00,2023-11-21 20:00:00,2023-11-21 19:00:00,2023-11-21 19:30:00,2023-11-21 19:00:00,2023-11-21 18:00:00,2023-11-21 19:00:00,2023-11-21 19:30:00,NaT,NaT,0.0,0.0,30.0,0.0,30.0,30.0,105.0,360.0,420.0,75.0,60.0,135.0,300.0,120.0,420.0,0.25,0.50,0.32
5,pepe,6,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 11:00:00,2023-11-21 13:00:00,2023-11-21 11:15:00,2023-11-21 14:00:00,2023-11-21 13:00:00,2023-11-21 14:00:00,2023-11-21 11:15:00,2023-11-21 13:00:00,2023-11-21 15:00:00,2023-11-21 11:00:00,0.0,120.0,165.0,60.0,105.0,180.0,390.0,360.0,465.0,210.0,105.0,315.0,300.0,120.0,420.0,0.70,0.88,0.75
6,pepe,7,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 11:00:00,2023-11-21 13:00:00,2023-11-21 15:00:00,2023-11-21 16:30:00,2023-11-21 15:00:00,2023-11-21 16:30:00,2023-11-21 11:00:00,2023-11-21 13:00:00,2023-11-21 15:00:00,2023-11-21 11:00:00,90.0,120.0,90.0,90.0,120.0,180.0,390.0,360.0,465.0,210.0,105.0,315.0,300.0,120.0,420.0,0.70,0.88,0.75
7,pepe,8,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 11:00:00,2023-11-21 13:00:00,2023-11-21 15:00:00,2023-11-21 17:30:00,2023-11-21 15:00:00,2023-11-21 17:30:00,2023-11-21 11:00:00,2023-11-21 13:00:00,2023-11-21 16:00:00,2023-11-21 11:00:00,90.0,120.0,150.0,150.0,120.0,180.0,390.0,360.0,465.0,210.0,105.0,315.0,300.0,120.0,420.0,0.70,0.88,0.75
8,pepe,9,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 11:00:00,2023-11-21 13:00:00,2023-11-21 16:00:00,2023-11-21 17:30:00,2023-11-21 16:00:00,2023-11-21 17:30:00,2023-11-21 11:00:00,2023-11-21 13:00:00,NaT,NaT,0.0,0.0,90.0,90.0,120.0,180.0,390.0,360.0,465.0,210.0,105.0,315.0,300.0,120.0,420.0,0.70,0.88,0.75

In [18]:
# Shift Dataframe

sh = df[['name', 'RosterStart', 'RosterEnd', 'OvertimeStart',
       'OvertimeEnd', 'RosterActive', 'OvertimeActive', 'DutyActive',
       'RosterShift', 'OvertimeShift', 'DutyShift', 'RosterUtilisation',
       'OvertimeUtilisation', 'DutyUtilisation']].drop_duplicates()

sh

,name,RosterStart,RosterEnd,OvertimeStart,OvertimeEnd,RosterActive,OvertimeActive,DutyActive,RosterShift,OvertimeShift,DutyShift,RosterUtilisation,OvertimeUtilisation,DutyUtilisation
0,nico,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 18:00:00,2023-11-21 20:00:00,75.0,60.0,135.0,300.0,120.0,420.0,0.25,0.50,0.32
5,pepe,2023-11-21 13:00:00,2023-11-21 18:00:00,2023-11-21 11:00:00,2023-11-21 13:00:00,210.0,105.0,315.0,300.0,120.0,420.0,0.70,0.88,0.75